fix exit code

diff --git a/.github/workflows/terraform_workflow_aws.yaml b/.github/workflows/terraform_workflow_aws.yaml
--- a/.github/workflows/terraform_workflow_aws.yaml
+++ b/.github/workflows/terraform_workflow_aws.yaml
@@ -35,8 +35,6 @@ jobs:
       
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_wrapper: false
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -51,17 +49,25 @@ jobs:
         run: terraform workspace select ${{ env.TF_WORKINGSPACE }} || terraform workspace new ${{ env.TF_WORKINGSPACE }}
       
       - name: Terraform Plan
+        id: plan
         run: |
           if [ "${{ github.event.inputs.action }}" = "apply" ]; then
-            terraform plan -input=false -out=${{ env.PLAN_FILE }} -detailed-exitcode; exitcode=$?
+            terraform plan -input=false -out=${{ env.PLAN_FILE }} 
           else
-            terraform plan -destroy -input=false -out=${{ env.PLAN_FILE }} -detailed-exitcode; exitcode=$?
+            terraform plan -destroy -input=false -out=${{ env.PLAN_FILE }}
           fi
-
-          if [ "$exitcode" -eq 2 ]; then
+      
+      - name: Check Plan status
+        run: |
+          if [ "${{ steps.plan.outputs.exitcode }}" -eq 2 ]; then
+            echo "Changes detected in plan" 
             echo "CHANGES_PRESENT=true" >> $GITHUB_ENV
-          else
+          elif [ "${{ steps.plan.outputs.exitcode }}" -eq 0 ]; then
+            echo "No Changes detected in plan" 
             echo "CHANGES_PRESENT=false" >> $GITHUB_ENV
+          else
+            echo "Error during plan"
+            exit 1
           fi
       
       - name: Wait for Approval
